.gitignore, package.json
- Add .gitignore
- Changed main file to src/bundle.js
=> Add missing dependencies

documentation/GettingStarted.md
=> Fixing image paths

.gitignore, .npmignore
Removing redundant file from npm
=> Removing redundant file from npm

src/raml1/ast.core/linter.ts, src/raml1/ast.core/mutators.ts
closes mulesoft-labs/api-workbench#2447.
=> Finding insertion point fix.

src/index.ts, src/raml1/artifacts/raml10parser.ts, src/raml1/artifacts/raml10parserapi.ts, src/raml1/ast.core/expander.ts, src/raml1/test/data/expander/expander_test_api17.raml, src/raml1/test/data/expander/expander_test_api17_exp.raml, src/raml1/test/data/expander/lib/lib.raml, src/raml1/test/traits-and-resource-types-expanding-tests.ts, src/raml1/wrapped-ast/wrapperHelper.ts
Fix https://github.com/raml-org/raml-js-parser-2/issues/163
=> Expanding templates declared in libraries

src/raml1/wrapped-ast/parserCore.ts, src/raml1/wrapped-ast/parserCoreApi.ts, src/util/TCKDumper.ts
Fixing https://github.com/raml-org/raml-js-parser-2/issues/44
=> toJSON() method for Attributes

src/raml1/ast.core/LowLevelASTProxy.ts, src/raml1/ast.core/expander.ts, src/raml1/ast.core/linter.ts, src/raml1/ast.core/typeBuilder.ts, src/raml1/test/TCK.ts, src/raml1/test/data/TCK/RAML10/Annotations 003/api-tck.json, src/raml1/test/data/TCK/RAML10/Traits/Trait 002/api-tck.json, src/raml1/test/data/TCK/RAML10/Traits/Trait 002/api.raml, src/raml1/test/data/parser/resourceType/resType21.raml, src/raml1/test/data/parser/resourceType/resType22.raml, src/raml1/test/parserTests.ts, src/raml1/test/parserTests2.ts
Making it possible to use objects as template parameter values:
```
resourceTypes:
rt1:
get: <<getMethodDefinition>>
/resource:
type:
rt1:
getMethodDefinition:
body:
application/json:
```
=> Object values for template parameters

src/raml1/test/data/parser/examples/ex13.raml, src/raml1/test/data/parser/examples/ex14.raml, src/raml1/test/data/parser/examples/ex15.raml, src/raml1/test/data/parser/examples/ex16.raml, src/raml1/test/data/parser/examples/ex17.raml, src/raml1/test/data/parser/examples/ex18.raml, src/raml1/test/data/parser/examples/ex19.raml, src/raml1/test/data/parser/examples/ex20.raml, src/raml1/test/data/parser/examples/ex21.raml, src/raml1/test/data/parser/examples/ex22.raml, src/raml1/test/data/parser/examples/ex23.raml, src/raml1/test/data/parser/examples/ex24.raml, src/raml1/test/data/parser/examples/ex25.raml, src/raml1/test/data/parser/examples/ex26.raml, src/raml1/test/data/parser/examples/ex27.raml, src/raml1/test/data/parser/examples/ex28.raml, src/raml1/test/data/parser/examples/ex29.raml, src/raml1/test/data/parser/examples/ex30.raml, src/raml1/test/data/parser/examples/ex33.raml, src/raml1/test/data/parser/examples/ex34.raml, src/raml1/test/data/parser/examples/ex40.raml, src/raml1/test/data/parser/examples/ex41.raml, src/raml1/test/data/parser/examples/ex43.raml, src/raml1/test/data/parser/examples/ex45.raml, src/raml1/test/data/parser/examples/ex46.raml, src/raml1/test/data/parser/examples/ex47.raml, src/raml1/test/data/parser/examples/ex8.raml, src/raml1/test/parserTests.ts, src/raml1/test/parserTests2.ts
Uncommenting some of the tests which now appear passing.
Getting rid of meaningless string literals in thjose tests which are ported to TCK
=> Tests cleaning

src/raml1/highLevelImpl.ts, src/raml1/test/data/TCK/RAML10/Examples/test052/api-tck.json, src/raml1/test/data/TCK/RAML10/Examples/test052/api.raml, src/raml1/test/data/TCK/RAML10/Examples/test052/examples/features.json, src/raml1/test/data/TCK/RAML10/Examples/test052/examples/features.yaml, src/raml1/test/data/TCK/RAML10/Examples/test052/types.raml
https://github.com/raml-org/raml-js-parser-2/issues/249
=> Fix for included yaml array examples

src/raml1/artifacts/raml10parserapi.ts, src/raml1/test/data/TCK/RAML10/Annotations/test030/api-tck.json, src/raml1/test/data/TCK/RAML10/Annotations/test030/api.raml, src/raml1/test/data/TCK/RAML10/Annotations/test031/api-tck.json, src/raml1/test/data/TCK/RAML10/Annotations/test031/api.raml, src/raml1/test/data/TCK/RAML10/Annotations/test031/lib.raml, src/raml1/test/data/TCK/RAML10/Annotations/test032/api-tck.json, src/raml1/test/data/TCK/RAML10/Annotations/test032/api.raml, src/raml1/test/data/TCK/RAML10/Annotations/test033/api-tck.json, src/raml1/test/data/TCK/RAML10/Annotations/test033/api.raml, src/raml1/test/data/TCK/RAML10/Annotations/test033/lib.raml, src/raml1/test/data/TCK/RAML10/Examples/test016/api-tck.json, src/raml1/test/data/TCK/RAML10/Examples/test017/api-tck.json, src/raml1/wrapped-ast/parserCore.ts, src/raml1/wrapped-ast/wrapperHelper.ts, src/util/TCKDumper.ts
Fix https://github.com/raml-org/raml-js-parser-2/issues/259
=> Array annotations fix

src/raml1/test/data/parser/jsonscheme/test11/apiInvalid.raml, src/raml1/test/data/parser/jsonscheme/test11/apiValid.raml, src/raml1/test/data/parser/jsonscheme/test2/apiInvalid.raml, src/raml1/test/data/parser/jsonscheme/test2/apiValid.raml, src/raml1/test/data/parser/jsonscheme/test3/apiInvalid.raml, src/raml1/test/data/parser/jsonscheme/test3/apiValid.raml, src/raml1/test/data/parser/jsonscheme/test4/apiInvalid.raml, src/raml1/test/data/parser/jsonscheme/test4/apiValid.raml, src/raml1/test/data/parser/jsonscheme/test6/apiInvalid.raml, src/raml1/test/data/parser/jsonscheme/test6/apiValid.raml, src/raml1/test/data/parser/jsonscheme/test9/apiInvalid.raml, src/raml1/test/data/parser/jsonscheme/test9/apiValid.raml, src/raml1/test/parserTests.ts
* Fixing draft 3/draft 4 issues.
* redirecting all web links to the present repo
* considering error messages
=> Restoring and fixing JSON schema tests

src/raml1/test/data/TCK/RAML10/Examples/test056/example.json, src/raml1/test/data/TCK/RAML10/Examples/test056/lib-tck.json, src/raml1/test/data/TCK/RAML10/Examples/test056/lib.raml, src/raml1/test/data/TCK/RAML10/Examples/test057/example.json, src/raml1/test/data/TCK/RAML10/Examples/test057/lib-tck.json, src/raml1/test/data/TCK/RAML10/Examples/test057/lib.raml, src/raml1/test/data/TCK/RAML10/Instagram1.0/api-tck.json, src/raml1/test/data/TCK/RAML10/Instagram1.0/examples/feed-example.json, src/raml1/test/data/TCK/RAML10/Instagram1.0/examples/media-example.json, src/raml1/test/data/TCK/RAML10/Instagram1.0/examples/ok-status-example.json, src/raml1/test/data/TCK/RAML10/Instagram1.0/types.raml, src/raml1/test/example-ramls/Instagram1.0/examples/feed-example.json, src/raml1/test/example-ramls/Instagram1.0/examples/media-example.json, src/raml1/test/example-ramls/Instagram1.0/examples/ok-status-example.json, src/raml1/test/example-ramls/Instagram1.0/types.raml, src/raml1/test/virtualFSTests.ts
=> Updating Instagram 1.0. Adding tests for null values of required

src/raml1/test/data/TCK/RAML10/Examples/test058/api-tck.json, src/raml1/test/data/TCK/RAML10/Examples/test058/api.raml, src/raml1/test/data/TCK/RAML10/Examples/test059/api-tck.json, src/raml1/test/data/TCK/RAML10/Examples/test059/api.raml, src/raml1/test/data/TCK/RAML10/Types/test006/apiInvalid-tck.json, src/raml1/test/data/TCK/RAML10/Types/test007/apiInvalid-tck.json, src/raml1/test/data/TCK/RAML10/Types/test008/apiInvalid-tck.json, src/raml1/test/data/TCK/RAML10/Types/test009/apiInvalid-tck.json
Adding tests for https://github.com/raml-org/raml-js-parser-2/issues/247
Fixing messags in TCk tests:
"union type options does not pass validation" => "Union type options do
not pass validation"
=> Adding tests for issue 247. Fixing error messages.

src/raml1/artifacts/raml10parser.ts, src/raml1/artifacts/raml10parserapi.ts, src/raml1/ast.core/builder.ts, src/raml1/highLevelImpl.ts, src/raml1/test/data/TCK/RAML10/Types/ObjectTypes/test012/oType12-tck.json, src/raml1/test/data/TCK/RAML10/Types/ObjectTypes/test012/oType12.raml, src/raml1/test/data/parser/resourceType/resType023.raml
* Fixing tests in order to handle `additionalProperties` property type change.
* Fixing propblem of `null` as single `type` value being not recognised
=> Fixing https://github.com/raml-org/raml-js-parser-2/issues/253

src/raml1/highLevelImpl.ts, src/raml1/test/data/TCK/RAML10/Types/ObjectTypes/test018/api-tck.json, src/raml1/test/data/TCK/RAML10/Types/ObjectTypes/test018/api.raml, src/raml1/test/data/TCK/RAML10/Types/ObjectTypes/test019/api-tck.json, src/raml1/test/data/TCK/RAML10/Types/ObjectTypes/test019/api.raml, src/raml1/test/data/TCK/RAML10/Types/ObjectTypes/test020/api-tck.json, src/raml1/test/data/TCK/RAML10/Types/ObjectTypes/test020/api.raml, src/raml1/test/data/TCK/RAML10/Types/ObjectTypes/test021/api-tck.json, src/raml1/test/data/TCK/RAML10/Types/ObjectTypes/test021/api.raml, src/raml1/test/data/TCK/RAML10/Types/ObjectTypes/test022/api-tck.json, src/raml1/test/data/TCK/RAML10/Types/ObjectTypes/test022/api.raml, src/raml1/wrapped-ast/parserCore.ts
Fixing https://github.com/raml-org/raml-js-parser-2/issues/280
=> Fixing https://github.com/raml-org/raml-js-parser-2/issues/280

src/raml1/ast.core/mutators.ts
closes mulesoft/api-workbench#237.
=> Shortcut type declaration modifying fix.

src/raml1/test/data/TCK/RAML10/Annotations/test034/api-tck.json, src/raml1/test/data/TCK/RAML10/Annotations/test034/api.raml
https://github.com/raml-org/raml-js-parser-2/issues/305
fix
=> Fixing tests in accordance with

src/raml1/ast.core/linter.ts, src/raml1/test/data/TCK/RAML10/Annotations/test006/apiInvalid-tck.json, src/raml1/test/data/TCK/RAML10/Annotations/test006/apiInvalid.raml, src/raml1/test/data/TCK/RAML10/Annotations/test006/apiInvalid1-tck.json, src/raml1/test/data/TCK/RAML10/Annotations/test006/apiValid-tck.json, src/raml1/test/data/TCK/RAML10/Annotations/test006/apiValid.raml, src/raml1/test/data/TCK/RAML10/Annotations/test006/apiValid1-tck.json, src/raml1/test/data/TCK/RAML10/Annotations/test006/apiValid1.raml, src/raml1/test/data/TCK/RAML10/Annotations/test011/apiInvalid-tck.json, src/raml1/test/data/TCK/RAML10/Annotations/test011/apiInvalid.raml, src/raml1/test/data/TCK/RAML10/Annotations/test011/apiValid-tck.json, src/raml1/test/data/TCK/RAML10/Annotations/test011/apiValid.raml, src/raml1/test/data/TCK/RAML10/Types/test003/apiInvalid-tck.json, src/raml1/test/data/TCK/RAML10/Types/test003/apiInvalid.raml, src/raml1/test/data/TCK/RAML10/Types/test003/apiValid-tck.json, src/raml1/test/data/TCK/RAML10/Types/test003/apiValid.raml, src/raml1/test/data/TCK/RAML10/Types/test005/apiInvalid-tck.json, src/raml1/test/data/TCK/RAML10/Types/test005/apiInvalid.raml, src/raml1/test/data/TCK/RAML10/Types/test005/apiValid-tck.json, src/raml1/test/data/TCK/RAML10/Types/test005/apiValid.raml, src/raml1/test/data/TCK/RAML10/Types/test012/apiInvalid-tck.json, src/raml1/test/data/TCK/RAML10/Types/test012/apiInvalid.raml, src/raml1/test/data/TCK/RAML10/Types/test012/apiValid-tck.json, src/raml1/test/data/TCK/RAML10/Types/test012/apiValid.raml
Issue fixed:
https://github.com/raml-org/raml-js-parser-2/issues/302
=> Fixing https://github.com/raml-org/raml-js-parser-2/issues/302

src/raml1/test/data/TCK/RAML10/Examples/test059/api-tck.json, src/raml1/test/data/TCK/RAML10/Types/test006/apiInvalid-tck.json, src/raml1/test/data/TCK/RAML10/Types/test007/apiInvalid-tck.json, src/raml1/test/data/TCK/RAML10/Types/test008/apiInvalid-tck.json, src/raml1/test/data/TCK/RAML10/Types/test009/apiInvalid-tck.json, src/raml1/test/helpersTest.ts
Caused by
https://github.com/raml-org/typesystem-ts/pull/64
=> Considering improved union types error messages in tests.

src/raml1/highLevelImpl.ts, src/raml1/test/data/TCK/RAML10/Examples/test063/example.raml, src/raml1/test/data/TCK/RAML10/Examples/test063/lib-tck.json, src/raml1/test/data/TCK/RAML10/Examples/test063/lib.raml
Issue fixed: https://github.com/raml-org/raml-js-parser-2/issues/333
=> Fixing error in ExampleSpec fragments inclusion

src/raml1/apiLoader.ts, src/raml1/jsyaml/jsyaml2lowLevel.ts
Issue fixed: https://github.com/raml-org/raml-js-parser-2/issues/323
=> Fixing spelling error

src/raml1/test/data/TCK/RAML10/Annotations/test008/apiInvalid-tck.json, src/raml1/test/data/TCK/RAML10/Annotations/test008/apiInvalid.raml, src/raml1/test/data/TCK/RAML10/Annotations/test008/apiValid-tck.json, src/raml1/test/data/TCK/RAML10/Annotations/test008/apiValid.raml, src/raml1/test/data/TCK/RAML10/Annotations/test009/apiInvalid-tck.json, src/raml1/test/data/TCK/RAML10/Annotations/test009/apiInvalid.raml, src/raml1/test/data/TCK/RAML10/Annotations/test009/apiValid-tck.json, src/raml1/test/data/TCK/RAML10/Annotations/test009/apiValid.raml, src/raml1/test/data/TCK/RAML10/Examples/test004/api-tck.json, src/raml1/test/data/TCK/RAML10/Examples/test004/api.raml, src/raml1/test/data/parser/annotations/a8.raml, src/raml1/test/data/parser/annotations/a9.raml, src/raml1/test/data/parser/examples/ex12.raml, src/raml1/test/data/parser/typexpressions/unions/types.raml
fixing https://github.com/raml-org/raml-js-parser-2/issues/304
=> Eliminating outdated pattern properties syntax: [] 

src/raml1/ast.core/linter.ts, src/raml1/highLevelImpl.ts, src/raml1/test/data/TCK/RAML10/Fragments/test006/Example1-tck.json, src/raml1/test/data/TCK/RAML10/Fragments/test006/Example1.raml, src/raml1/test/data/TCK/RAML10/Fragments/test006/Example2-tck.json, src/raml1/test/data/TCK/RAML10/Fragments/test006/Example2.raml, src/raml1/test/data/TCK/RAML10/Fragments/test006/Example3-tck.json, src/raml1/test/data/TCK/RAML10/Fragments/test006/Example3.raml, src/raml1/wrapped-ast/wrapperHelper.ts
fixing https://github.com/raml-org/raml-js-parser-2/issues/339
=> ExampleSpec fragment support

src/raml1/test/data/TCK/RAML10/Api/test018/api-tck.json, src/raml1/test/parserTestsRC2.ts
The https://github.com/raml-org/typesystem-ts/pull/68 pull request requires some messages to be changed in the tests.
=> Fixing error messages in tests

src/raml1/test/data/TCK/RAML10/Annotations/test015/apiInvalid-tck.json, src/raml1/test/data/TCK/RAML10/Annotations/test024/apiInvalid-tck.json, src/raml1/test/data/TCK/RAML10/Annotations/test025/apiInvalid-tck.json, src/raml1/test/data/TCK/RAML10/Examples/test008/api-tck.json, src/raml1/test/data/TCK/RAML10/Examples/test010/api-tck.json, src/raml1/test/data/TCK/RAML10/Examples/test011/api-tck.json, src/raml1/test/data/TCK/RAML10/Examples/test013/api-tck.json, src/raml1/test/data/TCK/RAML10/Examples/test014/api-tck.json, src/raml1/test/data/TCK/RAML10/Examples/test015/api-tck.json, src/raml1/test/data/TCK/RAML10/Examples/test017/api-tck.json, src/raml1/test/data/TCK/RAML10/Examples/test018/api-tck.json, src/raml1/test/data/TCK/RAML10/Examples/test020/api-tck.json, src/raml1/test/data/TCK/RAML10/Examples/test022/api-tck.json, src/raml1/test/data/TCK/RAML10/Types/ObjectTypes/test002/oType02-tck.json, src/raml1/test/data/TCK/RAML10/Types/ObjectTypes/test003/oType03-tck.json, src/raml1/test/data/TCK/RAML10/Types/PropertyOverride/test003/test3-tck.json, src/raml1/test/data/TCK/RAML10/Types/test019/api-tck.json, src/raml1/test/data/TCK/RAML10/Types/test026/api-tck.json, src/raml1/test/parserTests.ts, src/raml1/test/parserTests2.ts
Fixing tests according to https://github.com/raml-org/typesystem-ts/pull/69
=> Fixing tests

gulpfile.js, package.json, src/raml1/wrapped-ast/wrapperHelper.ts, src/raml1/wrapped-ast/wrapperHelper08.ts
Adding test coverage measurement to the parser test run. #370 fixed.
=> Parser test coverage

src/raml1/ast.core/linter.ts, src/raml1/test/data/TCK/RAML10/SecuritySchemes/test002/apiInvalid-tck.json, src/raml1/test/data/TCK/RAML10/SecuritySchemes/test002/apiInvalid.raml, src/raml1/test/data/TCK/RAML10/SecuritySchemes/test002/apiValid-tck.json, src/raml1/test/data/parser/method/meth13.raml, src/raml1/test/data/parser/method/meth14.raml, src/raml1/test/parserTests2.ts
=> Query parameters validation fix.

src/raml1/highLevelImpl.ts
https://github.com/raml-org/raml-js-parser-2/issues/358 fixed.
=> https://github.com/raml-org/raml-js-parser-2/issues/358 fixed.

src/raml1/artifacts/raml10parser.ts, src/raml1/artifacts/raml10parserapi.ts, src/raml1/wrapped-ast/wrapperHelper.ts
https://github.com/raml-org/raml-js-parser-2/issues/360 fixed.
=> https://github.com/raml-org/raml-js-parser-2/issues/360 fixed.

src/raml1/ast.core/linter.ts, src/raml1/test/data/TCK/RAML10/Types/test024/api-tck.json, src/raml1/test/data/TCK/RAML10/Types/test024/api.raml
=> disable examples sequence.

src/raml1/ast.core/linter.ts, src/raml1/jsyaml/json2lowLevel.ts, src/raml1/test/data/parser/annotations/a20.raml, src/raml1/test/parserTests.ts
=> null annotation fix.

src/raml1/ast.core/builder.ts, src/raml1/ast.core/referencePatcher.ts, src/raml1/highLevelImpl.ts, src/raml1/test/data/TCK/RAML10/ReferencesPatching/Fragments/test007/api-tck.json, src/raml1/test/data/TCK/RAML10/ReferencesPatching/Fragments/test007/api.raml, src/raml1/test/data/TCK/RAML10/ReferencesPatching/Fragments/test007/fragments/rt.raml, src/raml1/test/data/TCK/RAML10/ReferencesPatching/Fragments/test007/fragments/type.raml, src/raml1/test/data/TCK/RAML10/ReferencesPatching/Fragments/test007/libs/lib.raml, src/raml1/test/data/TCK/RAML10/ReferencesPatching/Fragments/test007/libs/types.raml, src/raml1/test/data/TCK/RAML10/ReferencesPatching/Fragments/test007/libs/types2.raml, src/raml1/test/data/TCK/RAML10/ReferencesPatching/Fragments/test008/api-tck.json, src/raml1/test/data/TCK/RAML10/ReferencesPatching/Fragments/test008/api.raml, src/raml1/test/data/TCK/RAML10/ReferencesPatching/Fragments/test008/fragments/rt.raml, src/raml1/test/data/TCK/RAML10/ReferencesPatching/Fragments/test008/fragments/type.raml, src/raml1/test/data/TCK/RAML10/ReferencesPatching/Fragments/test008/libs/lib.raml, src/raml1/test/data/TCK/RAML10/ReferencesPatching/Fragments/test008/libs/types.raml, src/raml1/test/data/TCK/RAML10/ReferencesPatching/Fragments/test008/libs/types2.raml
https://github.com/raml-org/raml-js-parser-2/issues/390
=> Fixing inlilned types

src/index.ts, src/raml1/test/data/TCK/RAML10/Annotations/test036/api-tck.json, src/raml1/test/data/TCK/RAML10/Annotations/test036/api.raml, src/raml1/test/data/TCK/RAML10/Annotations/test037/api-tck.json, src/raml1/test/data/TCK/RAML10/Annotations/test037/api.raml, src/raml1/test/data/vfsTests/invalidIncludeTest001/api.raml, src/raml1/test/data/vfsTests/invalidIncludeTest002/api.raml, src/raml1/test/helpersTest.ts, src/raml1/test/virtualFS/vfs.ts, src/raml1/test/virtualFSTests.ts
=> fixing parseRAML method signature

.npmignore, package.json, src/raml1/highLevelImpl.ts, src/util/TCKDumper.ts, src/util/contentprovider.ts
Reverts raml-org/raml-js-parser-2#375
=> Revert "fix typings exports to work with es6 projects"

.gitignore, .npmignore, package.json, src/devUtil/mainDTSLinkRemover.ts
Fix for https://github.com/raml-org/raml-js-parser-2/issues/365
=> Fix for 365

src/raml1/ast.core/linter.ts, src/raml1/test/data/TCK/RAML08/Examples/test003/api-tck.json, src/raml1/test/data/TCK/RAML08/Examples/test003/api.raml, src/raml1/test/data/TCK/RAML08/Instagram/api-tck.json, src/raml1/test/data/TCK/RAML08/ResourceTypes/test001/apiInvalid-tck.json, src/raml1/test/data/TCK/RAML08/ResourceTypes/test002/apiInvalid-tck.json, src/raml1/test/data/TCK/RAML08/ResourceTypes/test003/apiInvalid-tck.json, src/raml1/test/data/TCK/RAML08/ResourceTypes/test004/apiInvalid-tck.json, src/raml1/test/data/TCK/RAML08/ResourceTypes/test005/apiInvalid-tck.json, src/raml1/test/data/TCK/RAML08/Traits/test001/apiInvalid-tck.json, src/raml1/test/data/TCK/RAML08/Traits/test002/apiInvalid-tck.json, src/raml1/test/data/TCK/RAML08/Traits/test003/apiInvalid-tck.json, src/raml1/test/data/TCK/RAML08/Traits/test004/apiInvalid-tck.json
Fixing https://github.com/raml-org/raml-js-parser-2/issues/421
=> Examples failing validation produce warnings in RAML 0.8

generateBrowserVersion.js, package.json
=> Browsergen

documentation/GettingStarted.md, examples/highlevel-AST-usage/example-spec/api.raml, examples/highlevel-AST-usage/script.js, examples/highlevel-AST-usage/tutorial.md, src/raml1/highLevelAST.ts, workspace.json
https://github.com/raml-org/raml-js-parser-2/issues/503
=> Highlevel documentation

src/raml1/ast.core/linter.ts, src/raml1/test/data/TCK/raml-1.0/Types/xsdscheme/test009/apiInvalid-tck.json, src/raml1/test/data/TCK/raml-1.0/Types/xsdscheme/test009/apiInvalid.raml, src/raml1/test/data/TCK/raml-1.0/Types/xsdscheme/test009/apiValid-tck.json, src/raml1/test/data/TCK/raml-1.0/Types/xsdscheme/test009/apiValid.raml, src/raml1/test/data/TCK/raml-1.0/Types/xsdscheme/test009/root.xsd, src/raml1/test/data/TCK/raml-1.0/Types/xsdscheme/test009/schema1.xsd, src/util/schemaAsync.ts, src/util/xmlutil.ts, workspace.json
=> Xsdincludes

src/util/xmlutil.ts
=> Xsd schemes async loading fix.

src/raml1/tools/universeHelpers.ts
closes #mulesoft/api-workbench/390.
=> closes #mulesoft/api-workbench/390.

src/util/xmlutil.ts
closes raml-org/raml-js-parser-2#639.
=> closes raml-org/raml-js-parser-2#639.
